### ISSUE TITLE
去除微信 input[type=number] 最右边的 spinners

### ISSUE THREAD

**Issue by leecade** [leecade/webapp-debug#2]
默认在微信里会渲染一个特别畸形的 spinners

`-webkit-appearance: none;` 也移除不掉

**Comment by leecade** [comment]
``` css
input[type='number'] {
    -moz-appearance:textfield;
}
input[type=number]::-webkit-inner-spin-button,
input[type=number]::-webkit-outer-spin-button {
    -webkit-appearance: none;
    margin: 0;
}
```
