### ISSUE TITLE
rem 适配方案

### ISSUE THREAD

**Issue by leecade** [leecade/webapp-debug#5]
ref:

https://github.com/amfe/lib-flexible

Notice:
1. chrome font-size 没法渲染为 12px 以下, 所以基准值必须考虑
2. 测试微信在初次打开可能会设置缩放比例后, 未进行渲染, 刷新后能正常

**Comment by leecade** [comment]
降级:

``` css
html { font-size: 62.5%; }
body { font-size: 14px; font-size: 1.4rem; } /* =14px */
h1 { font-size: 24px; font-size: 2.4rem; } /* =24px */
```

**Comment by leecade** [comment]
``` css
html {
  font-size: 20px;
}
@media only screen and (min-width: 400px) {
  html {
    font-size: 21.33333333px !important;
  }
}
@media only screen and (min-width: 414px) {
  html {
    font-size: 22.08px !important;
  }
}
@media only screen and (min-width: 480px) {
  html {
    font-size: 25.6px !important;
  }
}
```

``` less
//
// Rem
// --------------------------------------------------

// Vertical screen

//375屏幕为 20px，以此为基础计算出每一种宽度的字体大小
//375以下不变，375以上等比放大

@baseWidth: 375px;
@baseFont: 20px;

html {
  font-size: @baseFont;  //默认当做320px宽度的屏幕来处理
}

@bps: 400px, 414px, 480px; 

.loop(@i: 1) when (@i <= length(@bps)) {  //注意less数组是从1开始的
  @bp: extract(@bps, @i);
  @font: @bp/@baseWidth*@baseFont;  
  @media only screen and (min-width: @bp){
    html {
      font-size: @font !important;
    }
  }
  .loop((@i + 1));
};
.loop;
```
